In [2]:
import pandas as pd
import numpy as np
from tqdm import tqdm

In [2]:
class_metrics_results = pd.read_csv('class_metrics_results.csv')
class_metrics_results = class_metrics_results.replace([np.inf, -np.inf], np.nan)

Let's also take square root of the fitness of the kruskal's stress function, because we were computing it without square root.

In [3]:
class_metrics_results['best_fitness_pso_kruskal'] = np.sqrt(class_metrics_results['best_fitness_pso_kruskal'])
class_metrics_results['best_fitness_ga_kruskal'] = np.sqrt(class_metrics_results['best_fitness_ga_kruskal'])

In [4]:
class_metrics_results.head()

,project_name,k,best_solution_pso_sammon,best_solution_pso_kruskal,best_fitness_pso_sammon,best_fitness_pso_kruskal,best_solution_ga_sammon,best_solution_ga_kruskal,best_fitness_ga_sammon,best_fitness_ga_kruskal
0,AlbertMN_AssistantComputerControl,1,[0.30184268 0.71259566 0.47909838 0.18215133 0...,[0.53353498 0.70237942 0.77112013 0.96077905 0...,0.312327,0.554072,[0.85906677 0.02970998 0.17407007 0.06994461 0...,[0.50541908 0.34814961 0.38141376 0.53018564 0...,0.233781,0.478107
1,AlbertMN_AssistantComputerControl,2,[0.56257 0.41260525 0.44744112 0.59925832 0...,[2.63092245e-01 6.03771062e-01 6.84342775e-01 ...,0.096674,0.477495,[0.87249911 0.65171961 0.42134027 0.05821091 0...,[0.3488852 0.58432847 0.23523724 0.93514499 0...,0.145951,0.304327
2,AlbertMN_AssistantComputerControl,3,[0.67533792 0.53320457 0.47141303 0.08081611 0...,[0.57725264 0.6406952 0.35128635 0.51142508 0...,0.117836,0.418325,[0.52369778 0.51048628 0.46880887 0.40506316 0...,[0. 0.60402126 0.82069364 0.3983824 0...,0.037846,0.182149
3,AlbertMN_AssistantComputerControl,4,[0.20582572 0.45777056 0.11976711 0.63522413 0...,[0.74439843 0.36269581 0.64364392 0.4777374 0...,0.051280,0.296486,[0.11391989 0.60649013 0.32785631 0.57786571 0...,[0. 0.92341608 0.47733755 0. 0...,0.022953,0.087155
4,AlbertMN_AssistantComputerControl,5,[0.58407171 0.64901711 0.43288412 0.42125581 0...,[0.15729195 0. 0. 0.86539103 0...,0.039125,0.331052,[0.1076678 0.79830757 0.54581672 0.39997535 0...,[0.48605504 0. 0.74380065 0.25196669 0...,0.004504,0.134028

In [5]:
method_metrics_results = pd.read_csv('method_metrics_results.csv')
method_metrics_results = method_metrics_results.replace([np.inf, -np.inf], np.nan)

method_metrics_results['best_fitness_pso_kruskal'] = np.sqrt(method_metrics_results['best_fitness_pso_kruskal'])
method_metrics_results['best_fitness_ga_kruskal'] = np.sqrt(method_metrics_results['best_fitness_ga_kruskal'])

In [6]:
method_metrics_results.head()

,project_name,k,best_solution_pso_sammon,best_solution_pso_kruskal,best_fitness_pso_sammon,best_fitness_pso_kruskal,best_solution_ga_sammon,best_solution_ga_kruskal,best_fitness_ga_sammon,best_fitness_ga_kruskal
0,AlbertMN_AssistantComputerControl,1,[0.33842509 0.14104911 0.17035333 0.81927272 0...,[0.23145529 0.81271415 0.57721486 0.71921722 0...,0.262679,0.504707,[0.35912039 0.80806554 0.67479296 0.56151408 0...,[0.48678102 0.92985609 0.79119693 0.57478863 0...,0.262679,0.504707
1,AlbertMN_AssistantComputerControl,2,[0.24405845 0.10051494 0.29555875 0.44421821 0...,[0.25510563 0.60142666 0.51712963 0.67581699 0...,0.113927,0.369975,[0.51637246 0.58649209 0.84027136 0.51717506 0...,[0.71336564 0.66671921 0.5953382 0. 0...,0.113927,0.335417
2,AlbertMN_AssistantComputerControl,3,[0.45713932 0.34307434 0.28087097 0.4249893 0...,[0.35837355 0.45918617 0.55024746 0.58685236 0...,0.051594,0.226123,[0.24636042 0.67486472 0.58991717 0.33521308 0...,[0.20737732 0.06667511 0.53663301 0.07525715 0...,0.051594,0.226123
3,AlbertMN_AssistantComputerControl,4,[0.39230196 0.1981524 0.5124487 0.25918181 0...,[0.43272354 0.55195326 0.41722024 0.07702634 0...,0.020183,0.135135,[0.70390693 0.4709927 0.85034828 0.24817465 0...,[0.53815309 0.785006 0.57788491 0.57098986 0...,0.020183,0.135135
4,AlbertMN_AssistantComputerControl,5,[0.33596218 0.30197266 0.5288556 0.41584004 0...,[0.55372845 0.3853915 0.36491927 0.87423386 0...,0.009463,0.128577,[0.66905065 0.233893 0.04362728 0.33127489 0...,[0. 0.17915832 0.29924098 0.29046895 0...,0.009463,0.075066

# Hypothesis 1: Comparing PSO and GA

For Sammon's stress function and Kruskal's stress function, as well as for class level metrics and method level metrics, we will compare the results of PSO and GA using the Mann-Whitney test at each k.

In [11]:
class_k_max = class_metrics_results['k'].max()
method_k_max = method_metrics_results['k'].max()

In [42]:
from scipy.stats import mannwhitneyu


def mann_whitney_test(df, error_fun, k):
    pso = df[df['k'] == k]['best_fitness_pso_' + error_fun].dropna()
    ga = df[df['k'] == k]['best_fitness_ga_' + error_fun].dropna()
    return mannwhitneyu(pso, ga), pso.mean(), ga.mean()

mann_whitney_test(class_metrics_results, 'sammon', 2)

(MannwhitneyuResult(statistic=10783.5, pvalue=2.8088867425165656e-14),
 0.1737879799233015,
 0.10745929527444743)

In [43]:
class_level_hyp1_results = pd.DataFrame(columns=['k', 'sammon', 'kruskal', 'pso_mean_sammon', 'ga_mean_sammon', 'pso_mean_kruskal', 'ga_mean_kruskal'])
for k in tqdm(range(1, class_k_max + 1)):
    test_sammon, pso_mean_sammon, ga_mean_sammon = mann_whitney_test(class_metrics_results, 'sammon', k)
    test_kruskal, pso_mean_kruskal, ga_mean_kruskal = mann_whitney_test(class_metrics_results, 'kruskal', k)
    class_level_hyp1_results = class_level_hyp1_results.append({
        'k': k,
        'sammon': test_sammon.pvalue,
        'kruskal': test_kruskal.pvalue,
        'pso_mean_sammon': pso_mean_sammon,
        'ga_mean_sammon': ga_mean_sammon,
        'pso_mean_kruskal': pso_mean_kruskal,
        'ga_mean_kruskal': ga_mean_kruskal
    }, ignore_index=True)

class_level_hyp1_results['k'] = class_level_hyp1_results['k'].astype(int)
class_level_hyp1_results

100%|██████████| 40/40 [00:00<00:00, 298.51it/s]

,k,sammon,kruskal,pso_mean_sammon,ga_mean_sammon,pso_mean_kruskal,ga_mean_kruskal
0,1,1.802840e-02,3.899033e-02,2.771693e-01,2.500355e-01,0.491134,4.649650e-01
1,2,2.808887e-14,6.268162e-15,1.737880e-01,1.074593e-01,0.384773,2.824967e-01
2,3,1.063798e-23,1.172236e-22,1.248205e-01,5.578798e-02,0.317222,1.792431e-01
3,4,6.085270e-21,7.493503e-28,8.571762e-02,3.214061e-02,0.269561,1.263011e-01
4,5,3.137831e-21,4.122570e-24,6.712862e-02,2.291214e-02,0.214185,8.629473e-02
5,6,5.402332e-29,9.081145e-29,5.722135e-02,1.485659e-02,0.191744,6.751576e-02
6,7,9.374182e-22,3.361157e-28,4.591483e-02,1.230228e-02,0.166933,5.691166e-02
7,8,5.364418e-25,1.305646e-26,3.485852e-02,8.455300e-03,0.144238,4.591077e-02
8,9,2.874879e-26,8.168670e-26,2.699148e-02,6.008064e-03,0.122679,3.631473e-02
9,10,3.917559e-26,1.227617e-26,2.173045e-02,4.542363e-03,0.110061,3.021833e-02
10,11,2.524436e-24,2.061886e-25,1.672555e-02,3.524231e-03,0.097407,2.819216e-02
11,12,4.307602e-24,1.334477e-27,1.576655e-02,2.966980e-03,0.093729,2.329080e-02
12,13,7.310654e-28,2.364854e-26,1.310095e-02,2.147444e-03,0.077665,2.083076e-02
13,14,4.430151e-25,4.676039e-25,9.487179e-03,1.694617e-03,0.072573,1.694657e-02
14,15,4.393477e-24,3.348265e-23,1.027747e-02,1.336105e-03,0.055362,1.550429e-02
15,16,4.679878e-22,1.615617e-23,6.515905e-03,1.219023e-03,0.047316,1.339994e-02
16,17,6.709018e-27,4.882855e-19,6.026598e-03,9.228224e-04,0.036117,1.129333e-02
17,18,6.910967e-24,2.239760e-23,3.807379e-03,6.518233e-04,0.034982,9.496359e-03
18,19,1.446312e-24,2.888776e-22,3.431513e-03,5.065538e-04,0.029769,8.325646e-03
19,20,1.451029e-26,1.866131e-24,2.289667e-03,3.801274e-04,0.028206,7.034976e-03
20,21,1.886122e-22,5.601647e-23,2.139243e-03,3.091266e-04,0.023916,5.868140e-03
21,22,1.475445e-24,1.210012e-23,1.624657e-03,2.252147e-04,0.020210,4.941800e-03
22,23,9.487378e-23,1.507551e-20,1.321242e-03,1.746943e-04,0.015730,4.336259e-03
23,24,3.773557e-21,3.651524e-21,1.140902e-03,1.272711e-04,0.012281,3.514268e-03
24,25,2.817747e-23,1.605006e-20,8.604951e-04,9.655077e-05,0.011413,2.985995e-03
25,26,6.716682e-23,8.033543e-23,4.704754e-04,6.254328e-05,0.010342,2.532660e-03
26,27,1.597906e-24,6.765900e-20,4.721973e-04,4.722294e-05,0.008016,1.971066e-03
27,28,3.395240e-22,5.148695e-22,2.863946e-04,3.447318e-05,0.006014,1.576323e-03
28,29,1.603322e-23,6.671705e-22,2.042316e-04,2.040285e-05,0.005438,1.212244e-03
29,30,5.745185e-20,5.010841e-25,1.437607e-04,1.326961e-05,0.004233,9.015196e-04
30,31,1.390259e-22,1.334009e-21,1.087806e-04,9.472621e-06,0.003089,6.473047e-04
31,32,1.196884e-18,1.987221e-20,4.948228e-05,5.661918e-06,0.002325,5.027399e-04
32,33,1.485000e-17,1.278609e-20,3.765743e-05,2.989551e-06,0.001779,3.399828e-04
33,34,2.588946e-18,5.719261e-19,2.097570e-05,1.810311e-06,0.001192,2.318636e-04
34,35,4.707326e-19,1.247027e-17,1.009074e-05,8.882598e-07,0.000727,1.341184e-04
35,36,2.965067e-14,2.754599e-15,4.591844e-06,3.219849e-07,0.000452,8.025223e-05
36,37,2.226825e-09,1.785562e-12,1.422146e-06,1.145358e-07,0.000191,3.215229e-05
37,38,3.424337e-06,4.446758e-08,2.070423e-07,1.256384e-08,0.000038,7.123764e-06
38,39,6.347395e-02,2.072013e-02,1.611675e-09,2.375727e-10,0.000003,7.749783e-07
39,40,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00

In [45]:
method_level_hyp1_results = pd.DataFrame(columns=['k', 'sammon', 'kruskal', 'pso_mean_sammon', 'ga_mean_sammon', 'pso_mean_kruskal', 'ga_mean_kruskal'])
for k in tqdm(range(1, method_k_max + 1)):
    test_sammon, pso_mean_sammon, ga_mean_sammon = mann_whitney_test(method_metrics_results, 'sammon', k)
    test_kruskal, pso_mean_kruskal, ga_mean_kruskal = mann_whitney_test(method_metrics_results, 'kruskal', k)
    method_level_hyp1_results = method_level_hyp1_results.append({
        'k': k,
        'sammon': test_sammon.pvalue,
        'kruskal': test_kruskal.pvalue,
        'pso_mean_sammon': pso_mean_sammon,
        'ga_mean_sammon': ga_mean_sammon,
        'pso_mean_kruskal': pso_mean_kruskal,
        'ga_mean_kruskal': ga_mean_kruskal
    }, ignore_index=True)

method_level_hyp1_results['k'] = method_level_hyp1_results['k'].astype(int)
method_level_hyp1_results

100%|██████████| 14/14 [00:00<00:00, 297.88it/s]

,k,sammon,kruskal,pso_mean_sammon,ga_mean_sammon,pso_mean_kruskal,ga_mean_kruskal
0,1,8.742369e-01,8.338492e-01,0.291720,0.290860,0.511700,0.510214
1,2,1.996055e-04,1.108612e-06,0.153096,0.135112,0.350209,0.322465
2,3,2.196543e-05,1.603524e-06,0.087006,0.071393,0.250044,0.214714
3,4,4.721687e-08,5.483110e-07,0.053801,0.038203,0.170292,0.135502
4,5,2.965086e-08,1.048575e-10,0.032217,0.021721,0.129671,0.089374
5,6,1.130428e-09,2.352488e-12,0.020036,0.012715,0.092620,0.058668
6,7,4.212217e-07,2.520290e-09,0.011914,0.007647,0.063616,0.039252
7,8,9.930878e-08,6.179445e-12,0.007513,0.004505,0.048025,0.026391
8,9,4.941046e-07,3.429038e-07,0.004000,0.002400,0.029515,0.017503
9,10,4.176509e-06,2.196809e-05,0.002059,0.001210,0.017813,0.011224
10,11,4.065055e-05,2.737180e-03,0.000824,0.000498,0.010226,0.006762
11,12,2.666839e-03,6.151864e-03,0.000231,0.000130,0.005052,0.003358
12,13,4.672224e-01,6.892644e-01,0.000010,0.000001,0.000195,0.000050
13,14,1.000000e+00,1.000000e+00,0.000000,0.000000,0.000000,0.000000

In [46]:
format_pvalue = lambda pvalue: f'{pvalue:.3f}' if pvalue > 0.001 else '<0.001'
format_mean = lambda mean: f'{mean:.3f}'

In [47]:
class_level_hyp1_results['sammon'] = class_level_hyp1_results['sammon'].apply(format_pvalue)
class_level_hyp1_results['kruskal'] = class_level_hyp1_results['kruskal'].apply(format_pvalue)
for col in ['pso_mean_sammon', 'ga_mean_sammon', 'pso_mean_kruskal', 'ga_mean_kruskal']:
    class_level_hyp1_results[col] = class_level_hyp1_results[col].apply(format_mean)
class_level_hyp1_results

,k,sammon,kruskal,pso_mean_sammon,ga_mean_sammon,pso_mean_kruskal,ga_mean_kruskal
0,1,0.018,0.039,0.277,0.250,0.491,0.465
1,2,<0.001,<0.001,0.174,0.107,0.385,0.282
2,3,<0.001,<0.001,0.125,0.056,0.317,0.179
3,4,<0.001,<0.001,0.086,0.032,0.270,0.126
4,5,<0.001,<0.001,0.067,0.023,0.214,0.086
5,6,<0.001,<0.001,0.057,0.015,0.192,0.068
6,7,<0.001,<0.001,0.046,0.012,0.167,0.057
7,8,<0.001,<0.001,0.035,0.008,0.144,0.046
8,9,<0.001,<0.001,0.027,0.006,0.123,0.036
9,10,<0.001,<0.001,0.022,0.005,0.110,0.030
10,11,<0.001,<0.001,0.017,0.004,0.097,0.028
11,12,<0.001,<0.001,0.016,0.003,0.094,0.023
12,13,<0.001,<0.001,0.013,0.002,0.078,0.021
13,14,<0.001,<0.001,0.009,0.002,0.073,0.017
14,15,<0.001,<0.001,0.010,0.001,0.055,0.016
15,16,<0.001,<0.001,0.007,0.001,0.047,0.013
16,17,<0.001,<0.001,0.006,0.001,0.036,0.011
17,18,<0.001,<0.001,0.004,0.001,0.035,0.009
18,19,<0.001,<0.001,0.003,0.001,0.030,0.008
19,20,<0.001,<0.001,0.002,0.000,0.028,0.007
20,21,<0.001,<0.001,0.002,0.000,0.024,0.006
21,22,<0.001,<0.001,0.002,0.000,0.020,0.005
22,23,<0.001,<0.001,0.001,0.000,0.016,0.004
23,24,<0.001,<0.001,0.001,0.000,0.012,0.004
24,25,<0.001,<0.001,0.001,0.000,0.011,0.003
25,26,<0.001,<0.001,0.000,0.000,0.010,0.003
26,27,<0.001,<0.001,0.000,0.000,0.008,0.002
27,28,<0.001,<0.001,0.000,0.000,0.006,0.002
28,29,<0.001,<0.001,0.000,0.000,0.005,0.001
29,30,<0.001,<0.001,0.000,0.000,0.004,0.001
30,31,<0.001,<0.001,0.000,0.000,0.003,0.001
31,32,<0.001,<0.001,0.000,0.000,0.002,0.001
32,33,<0.001,<0.001,0.000,0.000,0.002,0.000
33,34,<0.001,<0.001,0.000,0.000,0.001,0.000
34,35,<0.001,<0.001,0.000,0.000,0.001,0.000
35,36,<0.001,<0.001,0.000,0.000,0.000,0.000
36,37,<0.001,<0.001,0.000,0.000,0.000,0.000
37,38,<0.001,<0.001,0.000,0.000,0.000,0.000
38,39,0.063,0.021,0.000,0.000,0.000,0.000
39,40,1.000,1.000,0.000,0.000,0.000,0.000

In [48]:
method_level_hyp1_results['sammon'] = method_level_hyp1_results['sammon'].apply(format_pvalue)
method_level_hyp1_results['kruskal'] = method_level_hyp1_results['kruskal'].apply(format_pvalue)
for col in ['pso_mean_sammon', 'ga_mean_sammon', 'pso_mean_kruskal', 'ga_mean_kruskal']:
    method_level_hyp1_results[col] = method_level_hyp1_results[col].apply(format_mean)
method_level_hyp1_results

,k,sammon,kruskal,pso_mean_sammon,ga_mean_sammon,pso_mean_kruskal,ga_mean_kruskal
0,1,0.874,0.834,0.292,0.291,0.512,0.510
1,2,<0.001,<0.001,0.153,0.135,0.350,0.322
2,3,<0.001,<0.001,0.087,0.071,0.250,0.215
3,4,<0.001,<0.001,0.054,0.038,0.170,0.136
4,5,<0.001,<0.001,0.032,0.022,0.130,0.089
5,6,<0.001,<0.001,0.020,0.013,0.093,0.059
6,7,<0.001,<0.001,0.012,0.008,0.064,0.039
7,8,<0.001,<0.001,0.008,0.005,0.048,0.026
8,9,<0.001,<0.001,0.004,0.002,0.030,0.018
9,10,<0.001,<0.001,0.002,0.001,0.018,0.011
10,11,<0.001,0.003,0.001,0.000,0.010,0.007
11,12,0.003,0.006,0.000,0.000,0.005,0.003
12,13,0.467,0.689,0.000,0.000,0.000,0.000
13,14,1.000,1.000,0.000,0.000,0.000,0.000

Write the results to csv files

In [49]:
class_level_hyp1_results.to_csv('class_level_hyp1_results.csv', index=False)
method_level_hyp1_results.to_csv('method_level_hyp1_results.csv', index=False)

Format results for latex

In [52]:
for row in class_level_hyp1_results.iterrows():
    print(f"{row[1]['k']} & ${row[1]['sammon']}$ & ${row[1]['kruskal']}$ & ${row[1]['pso_mean_sammon']}$ & ${row[1]['ga_mean_sammon']}$ & ${row[1]['pso_mean_kruskal']}$ & ${row[1]['ga_mean_kruskal']}$ \\\\ \\hline")

1 & $0.018$ & $0.039$ & $0.277$ & $0.250$ & $0.491$ & $0.465$ \\ \hline
2 & $<0.001$ & $<0.001$ & $0.174$ & $0.107$ & $0.385$ & $0.282$ \\ \hline
3 & $<0.001$ & $<0.001$ & $0.125$ & $0.056$ & $0.317$ & $0.179$ \\ \hline
4 & $<0.001$ & $<0.001$ & $0.086$ & $0.032$ & $0.270$ & $0.126$ \\ \hline
5 & $<0.001$ & $<0.001$ & $0.067$ & $0.023$ & $0.214$ & $0.086$ \\ \hline
6 & $<0.001$ & $<0.001$ & $0.057$ & $0.015$ & $0.192$ & $0.068$ \\ \hline
7 & $<0.001$ & $<0.001$ & $0.046$ & $0.012$ & $0.167$ & $0.057$ \\ \hline
8 & $<0.001$ & $<0.001$ & $0.035$ & $0.008$ & $0.144$ & $0.046$ \\ \hline
9 & $<0.001$ & $<0.001$ & $0.027$ & $0.006$ & $0.123$ & $0.036$ \\ \hline
10 & $<0.001$ & $<0.001$ & $0.022$ & $0.005$ & $0.110$ & $0.030$ \\ \hline
11 & $<0.001$ & $<0.001$ & $0.017$ & $0.004$ & $0.097$ & $0.028$ \\ \hline
12 & $<0.001$ & $<0.001$ & $0.016$ & $0.003$ & $0.094$ & $0.023$ \\ \hline
13 & $<0.001$ & $<0.001$ & $0.013$ & $0.002$ & $0.078$ & $0.021$ \\ \hline
14 & $<0.001$ & $<0.001$ & $0.009$ & $0.002$ & $0.073$ & $0.017$ \\ \hline
15 & $<0.001$ & $<0.001$ & $0.010$ & $0.001$ & $0.055$ & $0.016$ \\ \hline
16 & $<0.001$ & $<0.001$ & $0.007$ & $0.001$ & $0.047$ & $0.013$ \\ \hline
17 & $<0.001$ & $<0.001$ & $0.006$ & $0.001$ & $0.036$ & $0.011$ \\ \hline
18 & $<0.001$ & $<0.001$ & $0.004$ & $0.001$ & $0.035$ & $0.009$ \\ \hline
19 & $<0.001$ & $<0.001$ & $0.003$ & $0.001$ & $0.030$ & $0.008$ \\ \hline
20 & $<0.001$ & $<0.001$ & $0.002$ & $0.000$ & $0.028$ & $0.007$ \\ \hline
21 & $<0.001$ & $<0.001$ & $0.002$ & $0.000$ & $0.024$ & $0.006$ \\ \hline
22 & $<0.001$ & $<0.001$ & $0.002$ & $0.000$ & $0.020$ & $0.005$ \\ \hline
23 & $<0.001$ & $<0.001$ & $0.001$ & $0.000$ & $0.016$ & $0.004$ \\ \hline
24 & $<0.001$ & $<0.001$ & $0.001$ & $0.000$ & $0.012$ & $0.004$ \\ \hline
25 & $<0.001$ & $<0.001$ & $0.001$ & $0.000$ & $0.011$ & $0.003$ \\ \hline
26 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.010$ & $0.003$ \\ \hline
27 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.008$ & $0.002$ \\ \hline
28 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.006$ & $0.002$ \\ \hline
29 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.005$ & $0.001$ \\ \hline
30 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.004$ & $0.001$ \\ \hline
31 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.003$ & $0.001$ \\ \hline
32 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.002$ & $0.001$ \\ \hline
33 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.002$ & $0.000$ \\ \hline
34 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.001$ & $0.000$ \\ \hline
35 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.001$ & $0.000$ \\ \hline
36 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.000$ & $0.000$ \\ \hline
37 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.000$ & $0.000$ \\ \hline
38 & $<0.001$ & $<0.001$ & $0.000$ & $0.000$ & $0.000$ & $0.000$ \\ \hline
39 & $0.063$ & $0.021$ & $0.000$ & $0.000$ & $0.000$ & $0.000$ \\ \hline
40 & $1.000$ & $1.000$ & $0.000$ & $0.000$ & $0.000$ & $0.000$ \\ \hline

In [53]:
for row in method_level_hyp1_results.iterrows():
    print(f"{row[1]['k']} & ${row[1]['sammon']}$ & ${row[1]['kruskal']}$ & ${row[1]['pso_mean_sammon']}$ & ${row[1]['ga_mean_sammon']}$ & ${row[1]['pso_mean_kruskal']}$ & ${row[1]['ga_mean_kruskal']}$ \\\\ \\hline")

1 & $0.874$ & $0.834$ & $0.292$ & $0.291$ & $0.512$ & $0.510$ \\ \hline
2 & $<0.001$ & $<0.001$ & $0.153$ & $0.135$ & $0.350$ & $0.322$ \\ \hline
3 & $<0.001$ & $<0.001$ & $0.087$ & $0.071$ & $0.250$ & $0.215$ \\ \hline
4 & $<0.001$ & $<0.001$ & $0.054$ & $0.038$ & $0.170$ & $0.136$ \\ \hline
5 & $<0.001$ & $<0.001$ & $0.032$ & $0.022$ & $0.130$ & $0.089$ \\ \hline
6 & $<0.001$ & $<0.001$ & $0.020$ & $0.013$ & $0.093$ & $0.059$ \\ \hline
7 & $<0.001$ & $<0.001$ & $0.012$ & $0.008$ & $0.064$ & $0.039$ \\ \hline
8 & $<0.001$ & $<0.001$ & $0.008$ & $0.005$ & $0.048$ & $0.026$ \\ \hline
9 & $<0.001$ & $<0.001$ & $0.004$ & $0.002$ & $0.030$ & $0.018$ \\ \hline
10 & $<0.001$ & $<0.001$ & $0.002$ & $0.001$ & $0.018$ & $0.011$ \\ \hline
11 & $<0.001$ & $0.003$ & $0.001$ & $0.000$ & $0.010$ & $0.007$ \\ \hline
12 & $0.003$ & $0.006$ & $0.000$ & $0.000$ & $0.005$ & $0.003$ \\ \hline
13 & $0.467$ & $0.689$ & $0.000$ & $0.000$ & $0.000$ & $0.000$ \\ \hline
14 & $1.000$ & $1.000$ & $0.000$ & $0.000$ & $0.000$ & $0.000$ \\ \hline

# Hypothesis 2: Comparing Sammon's error function for train and validation sets using found optimal subset of metrics

In [3]:
class_level_validation_results = pd.read_csv('class_level_validation_results.csv')
method_level_validation_results = pd.read_csv('method_level_validation_results.csv')

In [4]:
class_level_validation_results.head()

                                     project_name    sammon   kruskal
0                  machine_machine.specifications  0.011871  0.048665
1                     SaviorXTanren_mixer-mixitup  0.016818  0.052724
2  architecture-building-systems_revitpythonshell  0.001515  0.013174
3                        jaskie_PlayoutAutomation  0.012890  0.052608
4       digital-standard_ThreeDPoseUnityBarracuda  0.002686  0.052960

In [5]:
method_level_validation_results.head()

                                     project_name    sammon   kruskal
0                  machine_machine.specifications  0.017685  0.057967
1                     SaviorXTanren_mixer-mixitup  0.034943  0.071272
2  architecture-building-systems_revitpythonshell  0.013664  0.045242
3                        jaskie_PlayoutAutomation  0.032570  0.082887
4       digital-standard_ThreeDPoseUnityBarracuda  0.007468  0.071111

According to the hypothesis, when applying the optimal subsets derived from the training set, Sammon's error on the validation set should be lower than 0.1. To test this hypothesis, we employed a one-tailed t-test, where the null hypothesis (H0) was that the mean Sammon's error using the optimal subsets is greater than or equal to 0.1, while the alternative hypothesis (H1) was that the mean error is less than 0.1.

In [9]:
from scipy.stats import ttest_1samp

class_level_hyp2_results = pd.DataFrame(columns=['sammon_p_value', 'kruskal_p_value', 'sammon_mean', 'kruskal_mean'])
test_sammon = ttest_1samp(class_level_validation_results['sammon'].dropna(), 0.05, alternative='less')
test_kruskal = ttest_1samp(class_level_validation_results['kruskal'].dropna(), 0.1, alternative='less')
class_level_hyp2_results = class_level_hyp2_results.append({
    'sammon_p_value': test_sammon.pvalue,
    'kruskal_p_value': test_kruskal.pvalue,
    'sammon_mean': class_level_validation_results['sammon'].mean(),
    'kruskal_mean': class_level_validation_results['kruskal'].mean()
}, ignore_index=True)

class_level_hyp2_results

   sammon_p_value  kruskal_p_value  sammon_mean  kruskal_mean
0    9.144276e-24     3.787436e-12     0.008511      0.037991

In [10]:
method_level_hyp2_results = pd.DataFrame(columns=['sammon_p_value', 'kruskal_p_value', 'sammon_mean', 'kruskal_mean'])
test_sammon = ttest_1samp(method_level_validation_results['sammon'].dropna(), 0.05, alternative='less')
test_kruskal = ttest_1samp(method_level_validation_results['kruskal'].dropna(), 0.1, alternative='less')
method_level_hyp2_results = method_level_hyp2_results.append({
    'sammon_p_value': test_sammon.pvalue,
    'kruskal_p_value': test_kruskal.pvalue,
    'sammon_mean': method_level_validation_results['sammon'].mean(),
    'kruskal_mean': method_level_validation_results['kruskal'].mean()
}, ignore_index=True)

method_level_hyp2_results

   sammon_p_value  kruskal_p_value  sammon_mean  kruskal_mean
0    2.923797e-08         0.000095     0.026571      0.067924

In [17]:
def scientific_notation_to_power_of_ten(number):
    number = str(number)
    if 'e' in number:
        base, exponent = number.split('e')
        return f'{float(base):.2f} \\times 10^{{{int(exponent)}}}'
    else:
        return number

In [18]:
print(f'Metric level & P-value & Sammon\'s mean error \\\\ \\hline')
print(f'Class level & ${scientific_notation_to_power_of_ten(class_level_hyp2_results["sammon_p_value"][0])}$ & ${class_level_hyp2_results["sammon_mean"][0]:.3f}$ \\\\ \\hline')
print(f'Method level & ${scientific_notation_to_power_of_ten(method_level_hyp2_results["sammon_p_value"][0])}$ & ${method_level_hyp2_results["sammon_mean"][0]:.3f}$ \\\\ \\hline')

Metric level & P-value & Sammon's mean error \\ \hline
Class level & $9.14 \times 10^{-24}$ & $0.009$ \\ \hline
Method level & $2.92 \times 10^{-8}$ & $0.027$ \\ \hline